### ISSUE TITLE
Authentication

### ISSUE THREAD

**Issue by Santana1053** [ggioffreda/git#1]
How do you integrate HTTPS/SSH authentication to push to a remote repository?

**Comment by ggioffreda** [comment]
SSH is the easiest option, you just need to make sure the user that's running the process has SSH access to the repository you want it to push to. Instructions for [GitHub](https://help.github.com/articles/adding-a-new-ssh-key-to-your-github-account/) and [BitBucket](https://confluence.atlassian.com/bitbucket/set-up-ssh-for-git-728138079.html) are available.

If you don't want to give access through SSH or for some reasons you can't, you can still use HTTPS to authenticate and it requires just a couple of more steps for both GitHub and BitBucket.

GitHub uses a [personal access token](https://github.com/blog/1509-personal-api-tokens) and you just need to rewrite the URI of your repository from `https://github.com/ggioffreda/git.git` to `https://[yourusername]:[yourpersonalaccesstoken]@github.com/ggioffreda/git.git`. Note that the personal access token is not your password.

BitBucket uses a [standard OAuth 2 authentication flow](https://confluence.atlassian.com/bitbucket/oauth-on-bitbucket-cloud-238027431.html) and once you get your access token you can rewrite the URI of your repository from `https://github.com/ggioffreda/git.git` to `https://x-token-auth:[youroauthaccesstoken]@github.com/ggioffreda/git.git`.

If you are looking for an example or something already written I've created two adapters that allows me to authenticate on both GitHub and BitBucket and [the source code is available](https://github.com/ggioffreda/git-guardian/tree/master/src/Adapter). If you want to reuse those feel free to require the package and write something like so:

```php
<?php

// namespace, uses, class definition and what not..
use Gioffreda\Component\GitGuardian\Adapter\GitHubRemote;
use Gioffreda\Component\GitGuardian\Adapter\GitHubRepository;
use Gioffreda\Component\GitGuardian\Adapter\BitBucketRemote;
use Gioffreda\Component\GitGuardian\Adapter\BitBucketRepository;

// and then inside your method somewhere...
$remote = new GitHubRemote();
$remote->setOptions(['personal_token' => 'your personal token here','username' => 'your username']);
$repository = new GitHubRepository('my repo', 'a brief description', 'https://github.com/ggioffreda/git-guardian.git'); // the anonymous URI is the third parameter
$repository->setRemote($remote);
$repository->getAnonimousUri(); // <-- this is what you passed to the constructor
$repository->getUri(); // <-- this is what you want, the URI with the personal token in it

// same code works for BitBucket with only one difference when you pass the credentials...
$remote = new BitBucketRemote();
$remote->setOptions(['client_id' => 'your client ID', 'client_secret' => 'your client secret']);
$repository = new BitBucketRepository('my repo', 'a brief description', 'https://bitbucket.com/ggioffreda/git-guardian.git'); // same parameters as above
$repository->setRemote($remote);
$repository->getAnonimousUri(); // <-- this is what you passed to the constructor
$repository->getUri(); // <-- this is what you want, the URI with the OAuth access token in it
```
(I haven't actually ran the code above but it should work as is unless there are typos)
